name: Deploy KefaloniaBnb

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-development:
    name: Deploy to Development
    runs-on: ubuntu-latest
    environment: development
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Create .env file
        run: |
          echo "STRIPE_PUBLIC_KEY=${{ secrets.STRIPE_PUBLIC_KEY }}" > .env
          echo "STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}" >> .env
          echo "BASE_PRICE_PER_NIGHT=200" >> .env
          echo "CLEANING_FEE=60" >> .env
          echo "ADDITIONAL_GUEST_FEE=0" >> .env
          echo "MIN_NIGHTS=2" >> .env
          echo "FRONTEND_URL=${{ secrets.FRONTEND_URL || 'https://dev.kefalonia-bnb.com' }}" >> .env
      
      - name: Build application
        run: npm run build
      
      # Add development deployment step here
      
  deploy-production:
    name: Deploy to Production
    needs: deploy-development
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Create .env file
        run: |
          echo "STRIPE_PUBLIC_KEY=${{ secrets.STRIPE_PUBLIC_KEY }}" > .env
          echo "STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}" >> .env
          echo "BASE_PRICE_PER_NIGHT=200" >> .env
          echo "CLEANING_FEE=60" >> .env
          echo "ADDITIONAL_GUEST_FEE=0" >> .env
          echo "MIN_NIGHTS=2" >> .env
          echo "FRONTEND_URL=${{ secrets.FRONTEND_URL || 'https://villakefalonia.potamianosgroup.com' }}" >> .env
      
      - name: Build application
        run: npm run build
      
      # Add production deployment step here
